### ISSUE TITLE
DOA

### ISSUE THREAD

**Issue by chrisdewar** [tsyd/proxy-tamper#6]
Seems like the proxy is DOA... or at least i can't get the first example to work...

    var proxy = require('proxy-tamper').start({ port: 8080 });
    proxy.tamper(/google.com/, 'tampered');

throws:

    /Users/chrisdewar/Documents/tools/tamper/node_modules/proxy-tamper/lib/proxy-tamper.js:132
    block.call(proxyTamper, proxyTamper);
          ^
    TypeError: Cannot call method 'call' of undefined
        at Object.exports.start (/Users/chrisdewar/Documents/tools/tamper/node_modules/proxy-tamper/lib/proxy-tamper.js:132:9)
        at Object.<anonymous> (/Users/chrisdewar/Documents/tools/tamper/tamper.js:1:99)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:901:3

**Comment by tsyd** [comment]
Fixed in 3756a076a26bf5d30dc762857ca71afdab473331.
